name: geoserver

on: [push]

jobs:
  build:
    env:
      DOCKER_ACCOUNT: sogis
      DOCKER_REPO: geoserver
      DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}      
      #BUILD_NUMBER: ${{GITHUB_RUN_NUMBER}}      
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Pull latest image 
        run: |
          docker pull $DOCKER_ACCOUNT/$DOCKER_REPO:2.18.0
      - name: Build image
        run: |
          docker build -t $DOCKER_ACCOUNT/$DOCKER_REPO:2.18.0 
      - name: Publish images
        run: |
          echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
          docker push $DOCKER_ACCOUNT/$DOCKER_REPO:2.18.0 
  
